server:
  port: 8080

spring:
  application:
    name: "Aviation Route Finder"
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    database-change-log-lock-table: AVIATION_DB_CHANGELOG_LOCK
    database-change-log-table: AVIATION_DB_CHANGE_LOG
    enabled: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost/aviation}
    username: ${POSTGRES_USER:aviation}
    password: ${POSTGRES_PASS:password}
  docker:
    compose:
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
        timeout: 10s
      file: docker-compose.yml

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: false
